name: touchmaster
description: "Touch Master application for sportsman in flutter"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'



dependencies:
  another_flutter_splash_screen: ^1.2.0
  badges: ^3.1.2
  blurrycontainer: ^1.0.2
  cached_network_image: ^3.2.3
  camera: ^0.10.5+5
  card_swiper: ^3.0.1
  chewie: ^1.7.4
  cool_dropdown: ^2.1.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^6.0.0
  flutter_chat_bubble: ^2.0.2
  flutter_svg: ^2.0.7
  flutter_svg_provider: null
  flutter_widget_from_html: ^0.14.11
  fluttertoast: ^8.2.4
  gallery_saver: ^2.3.2
  geocoding: ^2.1.1
  go_router: ^13.0.1
  google_fonts: ^4.0.4
  http: ^0.13.3
  image_cropper: ^4.0.1
  image_picker: ^1.0.0
  location: ^5.0.3
  motion_toast: ^2.7.8
  onboarding: ^3.1.0
  otp_text_field: ^1.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.1.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_gauges: ^23.1.40
  #  video_compress: ^3.1.0
  video_player: ^2.8.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  video_thumbnail: ^0.5.3

  video_compress:
    git:
      url: https://github.com/SpectoraSoftware/VideoCompress
      ref: caf41183e84adebd6ef5c8fba547937daf556a65 # Or master?
  dio: ^5.4.0
  flutter_cache_manager: ^3.3.1
  firebase_core: ^1.24.0
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^13.1.0
  cloud_firestore: ^3.5.1
  flutter_phone_direct_caller: ^2.1.1
  phone_state: ^1.0.3
  flutter_typeahead: ^5.1.0
  speech_to_text: ^6.6.0
  flutter_stripe: ^10.1.1


dependency_overrides:
  firebase_core_platform_interface: 4.5.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BankGothic
      fonts:
        - asset: assets/fonts/BankGothic Md BT.ttf
        - asset: assets/fonts/bankgothic-regular.ttf
          weight: 400
        - asset: assets/fonts/BankGothicMediumBT.ttf
          weight: 600
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
